# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Labo3_oef11.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AND_Port_0_0/design_1_AND_Port_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AND_Port_0_0 || ORIG_REF_NAME==design_1_AND_Port_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AND_Port_0_1/design_1_AND_Port_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AND_Port_0_1 || ORIG_REF_NAME==design_1_AND_Port_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AND_Port_1_0/design_1_AND_Port_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AND_Port_1_0 || ORIG_REF_NAME==design_1_AND_Port_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AND_Port_1_1/design_1_AND_Port_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AND_Port_1_1 || ORIG_REF_NAME==design_1_AND_Port_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_XOR_port_0_0/design_1_XOR_port_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_XOR_port_0_0 || ORIG_REF_NAME==design_1_XOR_port_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AND_Port_3_0/design_1_AND_Port_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AND_Port_3_0 || ORIG_REF_NAME==design_1_AND_Port_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_XOR_port_0_1/design_1_XOR_port_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_XOR_port_0_1 || ORIG_REF_NAME==design_1_XOR_port_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AND_Port_4_0/design_1_AND_Port_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AND_Port_4_0 || ORIG_REF_NAME==design_1_AND_Port_4_0} -quiet] -quiet

# XDC: c:/devWorks/Labo3_oef11/Labo3_oef11.gen/sources_1/bd/design_1/design_1_ooc.xdc
