set_property IOSTANDARD LVCMOS33 [get_ports led0]
set_property IOSTANDARD LVCMOS33 [get_ports sw0]
set_property IOSTANDARD LVCMOS33 [get_ports sw1]
set_property PACKAGE_PIN M19 [get_ports sw0]
set_property PACKAGE_PIN R14 [get_ports led0]
set_property PACKAGE_PIN M20 [get_ports sw1]
